apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: gateway-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: fanglyhome@gmail.com
    privateKeySecretRef:
      name: gateway-issuer-key
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: gateway-prod-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: fanglyhome@gmail.com
    privateKeySecretRef:
      name: gateway-prod-issuer-key
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gateway-tls
  namespace: smtrack
spec:
  secretName: gateway-tls-cert
  issuerRef:
    name: gateway-issuer
    kind: ClusterIssuer
  commonName: api.siamatic.dev
  dnsNames:
  - api.siamatic.dev
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gateway-prod-tls
  namespace: smtrack
spec:
  secretName: gateway-prod-tls-cert
  issuerRef:
    name: gateway-prod-issuer
    kind: ClusterIssuer
  commonName: tms.siamatic.co.th
  dnsNames:
  - tms.siamatic.co.th