apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: smtrack
spec:
  replicas: 4
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: siamatic/gateway:1.0.0
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 9090
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /__health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 30
          timeoutSeconds: 15
          successThreshold: 1
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /__health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 30
          timeoutSeconds: 15
          failureThreshold: 5
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
          limits:
            memory: 128Mi
            cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: smtrack
  labels:
    app: gateway 
spec:
  selector:
    app: gateway
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: monitor
      protocol: TCP
      port: 9090
      targetPort: 9090
  type: ClusterIP
